# Generated by Django 5.2.7 on 2025-10-29 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Transações'},
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='transacao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('tipo_categoria', models.CharField(choices=[('entrada', 'Receita'), ('saida', 'Despesa')], default='saida', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contas',
                'ordering': ['nome'],
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.conta'),
            preserve_default=False,
        ),
    ]
