# Generated by Django 5.2.7 on 2025-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('descricao', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=60)),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('parcelas', models.IntegerField(default=1)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
    ]
