# Generated by Django 5.2.7 on 2025-11-05 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_em', models.IntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano')], default=1, verbose_name='Série do Ensino Médio')),
                ('ano_registro', models.IntegerField(default=2025)),
                ('concluiu', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
