# Generated by Django 5.2.7 on 2025-11-07 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilaluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_alvo', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('conta_vinculada', models.OneToOneField(blank=True, help_text='Conta separada onde o dinheiro desta meta será depositado.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['data_alvo'],
            },
        ),
    ]
