# Generated by Django 5.2.7 on 2025-11-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_metafinanceira'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
