# Generated by Django 5.2.7 on 2025-11-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilaluno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
